name: Validate CSV of URLs and deploy changes
on: [push]

jobs:
  test-and-deploy-urls:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: Install dependencies
      run: pip install -r build-short-urls/requirements.txt --upgrade pip
          pip install pylint

    - name: Lint code
      run: cd build-short-urls && pylint *.py

    - name: validate CSV
      run: python build-short-urls/validate_redirects.py

    - name: deploy short URLs
      run: python build-short-urls/build_redirects.py
      env: # Or as an environment variable
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
